#!/bin/sh

# Mount file systems
mount -t proc /proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /dev

# Create essential devices
mkdir /dev/pts
mknod /dev/console c 5 1
mknod /dev/null c 1 3

#udevd --daemon
udevstart

echo -e '\033[0m\033[2J\033[HFirst stage loader' > /dev/tty0

# Wait for SD card
echo 'Detecting SD card...' > /dev/tty0
if [ "$(cat /proc/jz/mmc)" == "INSERT" ]; then
        timeout=20
        until [ -b /dev/mmcblk0 ]; do
                sleep 1
                timeout=`expr $timeout - 1`
                udevstart
                [ $timeout == 0 ] && break;
        done
fi

# Try to mount a fat32 partition from SD card
if [ -b /dev/mmcblk0 ]; then
        echo 'Mounting SD card...' > /dev/tty0
        for f in /dev/mmcblk0*; do
                mount $f /mnt/mmc -t vfat -o iocharset=cp936,codepage=936 && break
        done
fi

# Check upgrade.bin exists
img=/mnt/mmc/initfs.bin
if [ -f $img ]; then
        mkdir -p /mnt/root
        mount -t ext2 -o ro $img /mnt/root
fi

# Check rootfs mounted
if [ -f /mnt/root/init ]; then
        # Success, confirm switching root
        echo "Press any key in 1 second to abort root switching..."
        if ! read -t1 -n1 key; then
                # Prepare to switch root
                echo 'Switching root...' > /dev/tty0
                # Now, switch root
                umount -l /mnt/mmc
                umount -l /dev
                umount -l /sys
                umount -l /proc
                cd /mnt/root
                pivot_root . tmp
                # Unmount old root
                exec chroot . sh -c "
                umount -l /tmp
                exec /sbin/init" < /dev/console > /dev/console 2>&1
                #exec switch_root /mnt/root /init
        fi
fi

# Error fallback, boot busybox
echo -e '\033[1;31mLoader failed, booting busybox\033[0m' > /dev/tty0
echo "Press any key in 1 second to abort root switching..."
if ! read -t1 -n1 key; then
        # Prepare to switch root
        echo 'Switching root...' > /dev/tty0
        # Now, switch root
        umount -l /mnt/mmc
        umount -l /dev
        umount -l /sys
        umount -l /proc
        exec /bin/busybox init
fi

# Setup USB network for debugging
insmod /lib/modules/2.6.24.3/kernel/drivers/usb/gadget/jz4740_udc.ko use_dma=0
insmod /lib/modules/2.6.24.3/kernel/drivers/usb/gadget/g_ether.ko

ip addr add 192.168.2.2/24 dev usb0
ip link set usb0 up
ip route add default via 192.168.2.1

telnetd -l /bin/sh

# Error fallback, drop serial port to init shell
echo -e '\033[1;31mLoader failed!' > /dev/tty0
PS1="(initramfs) \w \$ " exec /bin/sh
