#! /bin/sh

MMC_STATUS=`cat /proc/jz/mmc`
UDC_STATUS=`cat /proc/jz/udc`
USB_STORAGE_STATUS=`/sbin/lsmod | grep "g_file_storage"`
MMC_DEVICE_NAME=`/sbin/mmc_fat_check`

echo  $1  > /tmp/2222
echo  "action="$ACTION  >> /tmp/2222
echo  "product="$PRODUCT >> /tmp/2222 
echo  "type="$TYPE >> /tmp/2222
echo  "interface="$INTERFACE  >> /tmp/2222


case $1 in
	usb)
	if [ "$ACTION" = "add" ];then
           if [ "$INTERFACE" = "3/1/2" ];then
             /sbin/hotplug_qcop "usbmouse-add" 
           fi 
        else 
           if [ "$ACTION" = "remove" ];then
              if [ "$INTERFACE" = "3/1/2" ];then
                /sbin/hotplug_qcop "usbmouse-remove"                                       
              fi
           fi  
        fi
	;;

	udc)
		if [ "$ACTION" = "add" ] ;then
		  /sbin/insmod /lib/modules/jz4730_udc.o udc_debug=1
		  /sbin/insmod /lib/modules/g_file_storage.o file=/dev/ssfdc1
		  sleep 1
		  UDC_STATUS=`cat /proc/jz/udc`
		
		 	if [ $UDC_STATUS = "INSERT_CABLE" ];then
				/sbin/rmmod g_file_storage
				/sbin/rmmod jz4740_udc
			  	/sbin/hotplug_qcop "cable" "add"
			else
	        		/sbin/hotplug_qcop "power" "add"
				/sbin/rmmod g_file_storage
				/sbin/rmmod jz4740_udc
			fi
	  	else
	  		if [ -n "$USB_STORAGE_STATUS" ] ;then	
				/sbin/rmmod g_file_storage
				/sbin/rmmod jz4740_udc
			fi
			if [ "$ACTION" = "remove-cable" ] ;then
				/sbin/hotplug_qcop "cable" "remove"
				#flushcache /dev/mtdblock8 
			else
				/sbin/hotplug_qcop "power" "remove"
			fi		
		fi
		;;
  	poweroff)
    		hotplug_qcop "poweroff" 
    		;;
	suspend)
		if [ "$ACTION" = "enter" ] ;then
	  		if [ -n "$USB_STORAGE_STATUS" ] ;then	
				echo "Don't  shutdown! do nothing"
			else
       				hotplug_qcop "suspend"
			fi
    		else 
       			hotplug_qcop "resume"

		fi
		;;
	keyboard)
	  	if [ -n "$USB_STORAGE_STATUS" ] ;then	
       			rmmod g_file_storage
       			rmmod jz4740_udc
       			/bin/np1kill all
		else
			if [ "$ACTION" = "killap" ] ;then
       				/bin/np1kill ap
    			else 
       				/bin/np1kill all
    			fi
		fi
		;;
       ssfdc)   #/sbin/flushcache  /dev/mtdblock8
        
               ;;
	*)
		;;
esac

